version: "2"
services:
  front:
    build: .
    container_name: load-balancer
    ports:
      - "5252:5252"
    command: --backends "http://bs1:80,http://bs2:80,http://bs3:80"
  bs1:
    image: strm/helloworld-http
  bs2:
    image: strm/helloworld-http
  bs3:
    image: strm/helloworld-http